const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    title: 'My Project API',
    description: 'API documentation generated by swagger-autogen',
  },
  host: 'localhost:5000',
  schemes: ['http'],
};

const outputFile = './swagger-output.json';
const endpointsFiles = ['./src/app.js']; // Path to the file with your routes

// This will generate the swagger-output.json file
swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    console.log("Swagger documentation has been generated.");
});
